### ISSUE TITLE
The hook example (dropdown component) on reference fly.io deploy isn't working

### ISSUE THREAD

**Issue by michaelterryio** [phenixdigital/phx_live_storybook_sample#4]
I was trying to integrate hooks with Storybook on my own project, but then noticed this reference deploy exhibits the same trouble I was having.

<img width="849" alt="2023-04-08_09-41-17" src="https://user-images.githubusercontent.com/57774951/230727490-a94976d7-8816-4282-a117-9e9be75ed254.png">

If I wanted to help out with this, any ideas what's going wrong?

c.f. phenixdigital/phoenix_storybook#284

Keywords for Google:

* No storybook configuration detected
* If you need to use custom hooks or `app.js` uploaders, please define them in JS file and declare this file in your Elixir backend module options (`:js_path_key`).
* Unknown hook found for "DropdownHook"

**Comment by cblavier** [comment]
Fixed in referenced https://github.com/phenixdigital/phoenix_storybook/issues/284
