### ISSUE TITLE
Cannot build Docker image

### ISSUE THREAD

**Issue by newt-beach** [phenixdigital/phx_live_storybook_sample#5]
On a fresh pull from `main`, attempting to create an image with `docker build .` fails with the following error:

`/app/deps/phoenix_storybook/assets/node_modules/yaml/dist/compose/composer.js:33`
`                if (prelude[i + 1]?.[0] !== '#')`
`                                   ^`
`SyntaxError: Unexpected token '.'`
`    at wrapSafe (internal/modules/cjs/loader.js:915:16)`
...
`npm ERR! code 1`
`npm ERR! path /app/deps/phoenix_storybook/assets`
`npm ERR! command failed`
`npm ERR! command sh -c tailwindcss --minify -i css/app.css -o ../priv/static/css/app.css`

Thank you ✌️ appreciate y'all building this example

**Comment by cblavier** [comment]
Hey, I remember I also had this issue.
Let me know if the latest Dockerfile (updated 1 or 2w ago) fixes it for you
